addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - psql -U postgres -c "create extension postgis"

script:
  - psql -U postgres -f create_functions.sql
  - psql --expanded -U postgres -f example.sql
