addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - psql -U postgres -c "create extension postgis"

script:
  - psql -U postgres -f create_functions.sql
  - psql --tuples-only --expanded -U postgres -f test/test.sql | tee test/actual_output.txt
  - diff test/expected_output.txt test/actual_output.txt
